### ISSUE TITLE
Products not showing on category page when Adaptive Device Pixel Ratios is enabled

### ISSUE THREAD

**Issue by dhorytskyi** [fastly/fastly-magento2#418] opened 2020-11-04 15:13 UTC
**Prerequisites:**
Magento 2.4 with Fastly-Magento module

**Steps to reproduce:**
1. Create a category
2. Create a product and assign it to the above-created category
3. Enable Fastly with the following settings:
Enable Deep Image Optimization = Yes
Enable Adaptive Device Pixel Ratios = Yes

**Actual result:**
Product does not appear

**Comment by MartinPeverelli** [comment] 2020-11-06 17:18
@dhorytskyi I don't think we can merge the PR as is, since we would then break support for <2.4 versions.
The API for the `custom_attributes` changed form `string` to `array` on this version, and that is the cause for the issue.

So, here is the proposal to close this issue, if merged: https://github.com/fastly/fastly-magento2/pull/422

**Comment by dhorytskyi** [comment] 2020-11-09 21:45
@MartinPeverelli Let's proceed with your PR, I've closed my one.

**Comment by vvuksan** [comment] 2020-11-10 14:40
We'll be part of 1.2.150.

**Closed by vvuksan** 2020-11-10 14:40 UTC
