### ISSUE TITLE
Fastly geoip redirect to the same store

### ISSUE THREAD

**Issue by mackendy** [fastly/fastly-magento2#242] opened 2019-01-16 19:48 UTC
If my default and current store are en_us and the popup come and offer me to switch to the en_ca store I am redirected to the current store en_us. I can reach the en_ca store with magento 2.2.6 and 2.2.7

**Comment by deninchoo** [comment] 2019-01-17 10:15
Hi @mackendy 

I am unable to reproduce this issue. Please make sure that you have the latest version of the Fastly extension (**1.2.80**) or at least version **1.2.76** or newer. Version **1.2.76** introduced a fix for an issue that you reported here https://github.com/fastly/fastly-magento2/issues/220 . Did that fix work for you?

If you already have the latest Fastly version, could you please tell me your exact GeoIP configuration or send me a screenshot?

**Comment by mackendy** [comment] 2019-01-17 13:00
thank you for the reply did you know any solution to test your feature in the local environment?

**Comment by deninchoo** [comment] 2019-01-18 14:40
Hey @mackendy ,

unfortunately I'm still having no luck with reproducing this issue and I'm still unsure why it's happening to you.

**Comment by deninchoo** [comment] 2019-02-18 14:00
Hi @mackendy ,

are you still experiencing this issue? If so, could you please tell me which Magento version and edition are you on? Is it the Community or Enterprise edition, or are you on the Cloud?

**Comment by Loxzibit** [comment] 2019-03-19 16:03
Hi @deninchoo 
I've also encountered the same issue on Magento Cloud Commerce edition after upgrading to 2.2.7 from 2.2.4. This was working fine before the upgrade.

We have store codes in the URLs in our case i.e.

http://www.example.com/uk
http://www.example.com/us
http://www.example.com/eu

**GEO IP Action:**
Redirect

**Comment by vvuksan** [comment] 2019-03-19 16:15
This doesn't appear to be a Fastly issue. Browser is triggering call to the store switcher however the store switcher is redirecting to the UK store e.g.

```$ curl -v -o /dev/null "https://www.CENSORED.com/uk/stores/store/switch/___store/eu/?___from_store=uk"
.....
< HTTP/2 302 
< content-security-policy: upgrade-insecure-requests
< content-type: text/html; charset=UTF-8
< expires: Mon, 19 Mar 2018 16:10:49 GMT
< location: https://www.CENSORED.com/uk/
```

same if I pick the US store.

**Comment by Loxzibit** [comment] 2019-03-19 16:47
**Status Update:**
I've also noticed Magento's site switcher passes the URL to switch to as a parameter *uenc* encoded in base64 based on the current URL

_Magento 2.2.7 Demo Store:_
http://104.237.149.38/magento227/stv1/

The switcher URL format is slightly different to the one generated by the Fastly module `\Fastly\Cdn\Controller\GeoIP\GetAction` controller
i.e. `stores/store/switch/___store/eu` vs the Magento's default `stores/store/switch/?___store=eu`:
http://104.237.149.38/magento227/default/stores/store/switch/?SID=p9bbmhm4senmara9v083guf3mm&___from_store=default&___store=stv1&uenc=aHR0cDovLzEwNC4yMzcuMTQ5LjM4L21hZ2VudG8yMjcvc3R2MS8_X19fc3RvcmU9c3R2MQ%2C%2C

**Comment by vvuksan** [comment] 2019-03-19 17:17
@Loxzibit pointed me to these two changes

https://github.com/magento/magento2/commit/8456ad054ec45cce6724d3cffbbdbeca3d372eb0

https://github.com/magento/magento2/commit/2aff06562bd2f62458e8e8f3b9fe639f36105f2f

**Comment by mackendy** [comment] 2019-03-19 18:40
Did someone find a solution?

**Comment by vvuksan** [comment] 2019-03-19 19:19
We are investigating now that we have a reproducible case.

**Comment by mackendy** [comment] 2019-03-20 12:57
Hi just for your information I add a little modification on your module because for exemple if i am on the canadian store and connect in the fr_ca store he ask me to be redirected to the en_ca.

so I add : 

+                // only generate a redirect URL if current and new website are different
+                if ($currentStore->getWebsiteId() != $targetStore->getWebsiteId()) {
+                    // only generate a redirect URL if current and new store are different
+                    if ($currentStore->getId() != $targetStore->getId()) {

**Comment by vvuksan** [comment] 2019-03-20 14:17
@mackendy can you submit that as a pull request and we'll review it.

Also can you test the patch in #254 to see if it addresses this issue.

**Comment by vvuksan** [comment] 2019-03-29 13:47
Fix released in 1.2.91.

**Comment by xi-ao** [comment] 2019-05-10 12:15
Hi @vvuksan,
We have the same issue after upgrading from Magento 2.2.3 to 2.2.8 and it doesn't seem to be fixed by the provided patch (we're using version 1.2.96 of the module).

After analysis, the cause seems to be the same as described earlier: the lack of `uenc` or `r64` parameter in the URL which is mandatory now in this version of Magento.

@mackendy I'm surprised, does the latest version really work with you?

**Comment by vvuksan** [comment] 2019-05-10 15:36
@xi-ao can you provide the list of URLs that are not working and what should be the correct URL format?

**Comment by Loxzibit** [comment] 2019-05-10 23:39
As an update, I've also installed the latest version (1.2.99) of the module on Magento Commerce edition 2.2.7 and couldn't get the GEO IP redirects to work.

**Comment by vvuksan** [comment] 2019-05-11 10:08
@Loxzibit It will be impossible to fix this without more details. Can you outline what steps you followed, what the behavior was, what the desired behavior should be etc.

**Comment by xi-ao** [comment] 2019-05-13 05:46
We're using Magento Cloud so all we've done was configuring the module in the back-office. We specified for example that if the visitor comes from a Spanish IP, he will be redirected to the ES store.

The problem currently - and since version 2.2.7 or so - is that the redirect URL that is generated by the Fastly module in `\Fastly\Cdn\Controller\GeoIP\GetAction::execute()` is like:
https://www.myshop.com/es/stores/store/switch/___store/es/?___from_store=uk (as mentioned above by @Loxzibit)

while it *should* be:
https://www.myshop.com/es/stores/store/switch/?SID=p9bbmhm4senmara9v083guf3mm&___from_store=uk&___store=es&uenc=aHR0cDovLzEwNC4yMzcuMTQ5LjM4L21hZ2VudG8yMjcvc3R2MS8_X19fc3RvcmU9c3R2MQ%2C%2C

The `uenc` query param is missing, but Magento now relies on it to perform the redirection.

**Comment by vvuksan** [comment] 2019-05-14 14:54
Fix has been included in version 1.2.102 of the plugin. Please try it out and if it doesn't work reopen this issue.

**Closed by vvuksan** 2019-05-14 14:54 UTC

**Comment by xi-ao** [comment] 2019-05-15 05:37
@vvuksan That seems much better. I'll give it a try. Thanks!

**Comment by Loxzibit** [comment] 2019-05-16 15:39
I can confirm that the Geo IP Redirects are now fixed and working as expected on **1.2.102** 🎉

**Comment by bharanikonda** [comment] 2020-01-02 09:27
Hi @vvuksan,

We are using the latest version of the plugin (fastly/magento2 - 1.2.122), but still we are seeing this issue. Our Magento version is 2.3.3. Can you please check and help us to resolve the issue.

**Comment by vvuksan** [comment] 2020-01-02 16:32
@bharanikonda can you elaborate on what is the behavior you are observing.

**Comment by a970032** [comment] 2020-02-24 09:27
hi i am facing the same problem now below is my setting
![image](https://user-images.githubusercontent.com/18587853/75140916-ceeb6e00-572a-11ea-830b-4a1d2d16013e.png)
when i enter the site with US ip it didnt redirect me to the store cn but to * store

**Comment by kayla-cheng** [comment] 2020-02-27 08:36
> hi i am facing the same problem now below is my setting
> ![image](https://user-images.githubusercontent.com/18587853/75140916-ceeb6e00-572a-11ea-830b-4a1d2d16013e.png)
> when i enter the site with US ip it didnt redirect me to the store cn but to * store

have you solved it?

**Comment by xi-ao** [comment] 2020-02-27 08:40
@a970032 What is the version of the module you're using?
The issue has been solved in versions 1.2.102+.

**Comment by kayla-cheng** [comment] 2020-02-27 08:51
> @a970032 What is the version of the module you're using?
> The issue has been solved in versions 1.2.102+.

1.2.114

**Comment by jupiter01** [comment] 2020-03-24 06:12
Same issue, Magento 2.3.4, Fastly 1.2.129

**Comment by jupiter01** [comment] 2020-03-25 22:03
@vvuksan This should be re-opened.
