### ISSUE TITLE
Introduce option to ignore custom parameters

### ISSUE THREAD

**Issue by kirmorozov** [fastly/fastly-magento2#102] opened 2017-09-13 15:09 UTC
Affiliate companies often use their own parameters.
https://github.com/fastly/fastly-magento2/blob/a96056f541ece95501a4bc635c93e7abf2f580ca/etc/vcl_snippets/recv.vcl#L71

Same option is already implemented in Magento dev branch for Varnish FPC.

**Comment by vvuksan** [comment] 2017-09-16 01:36
This was intended to cover large number of use cases. It's not an exhaustive list.

**Comment by kirmorozov** [comment] 2017-11-10 18:05
Its not nought, affiliate companies use special user Identifiers.
As a result we have miss cache.

**Comment by kirmorozov** [comment] 2017-11-10 18:06
Here is what I'm talking about:
https://github.com/fastly/fastly-magento/issues/33
https://github.com/iancassidyweb/magento2/commit/68fdecfcd26c957382b8d68b64887e0a83298524

**Comment by vvuksan** [comment] 2018-01-17 19:00
Fixed in #134. Will be part of 1.2.40 release.

**Closed by vvuksan** 2018-01-17 19:00 UTC
