### ISSUE TITLE
'Quick Purge' functionality doesn't work for static resources 

### ISSUE THREAD

**Issue by iskliarenko** [fastly/fastly-magento2#231] opened 2018-11-21 03:33 UTC
Hello Fastly team,

**Summary of issue**
Quick Purge functionality doesn't work for static resources (but works for 'HTML' URLs)

**Steps to replicate**

1. Install Fastly module (latest version) on the latest Magento (2.2.6)
2. Go to System -> Cache Management
3. Try to purge via 'Quick Purge' form any non-html URL like image, css, js etc, for example https://example.org/media/styles.css - notice an error message 'The purge request was not processed successfully.' (and there are no other errors in the logs).

However, it works fine for HTML pages, for example purging of 'https://example.org/what-is-new.html'
returns 'The URL's "https://example.org/what-is-new.html" cache has been cleaned.'

**Comment by vvuksan** [comment] 2018-11-21 03:39
I am unable to reproduce this behavior. Are you doing anything in your VCL that may be affecting non-HTML resources?

**Comment by vvuksan** [comment] 2019-02-06 13:45
We believe this was fixed in #245. Please try installing latest plugin to verify.

**Closed by vvuksan** 2019-02-06 13:45 UTC
