### ISSUE TITLE
GeoIP redirect URL contains both target and current store codes

### ISSUE THREAD

**Issue by mykolaoleksiuk** [fastly/fastly-magento2#616] opened 2023-02-28 18:54 UTC
I enabled Fastly GeoIP on my cloud instance.
I added country to store view mapping.
_Add store code to Urls_ configuration is enabled.
When customer is redirected to a target sotre the URL contains both current and target store codes.
Instead of redirecting from https://somedomain.com/de to https://somedomain.com/en it redirects to https://somedomain.com/en/de

**Comment by vvuksan** [comment] 2023-02-28 19:31
@bbutkovic @dpotkoc I thought we addressed this with #569. Can you investigate.

**Comment by bbutkovic** [comment] 2023-03-01 08:06
> @bbutkovic @dpotkoc I thought we addressed this with #569. Can you investigate.

We are looking into this.

**Comment by bbutkovic** [comment] 2023-03-01 13:16
Hello, @mykolaoleksiuk, thank you for reporting this issue with us.

Unfortunately, we were unable to reproduce the issue, could you just check a couple of things for us to help us get to the bottom of this?

- The version of Fastly Cdn module used
- Magento 2 version
- You have _Add Store Code to Urls_ enabled
- Your **Default Config** base URLs are set to `https://somedomain.com` (both for secure and non-secure). We're using `somedomain.com` as an example here.
- The base URLs for _de_ and _en_ stores are configured to either **use default** or **use website**.

In the case that the base URLs for _de_ or _en_ stores are not **use default** or **use website**, we'd like to ask you to let us know of any _overrides_ to the base URLs that you have applied to store/website config.

It could also be helpful to see your GeoIP redirection config.

One potential cause for this could be that your Magento 2 instance is configured to a different base URL for either the _en_ or _de_ stores and they resemble something along the lines of `https://somedomain.com/en` or `https://somedomain.com/de`

**Comment by mykolaoleksiuk** [comment] 2023-03-02 07:34
Hello @bbutkovic,

We spent some more time investigating the issue and found out that it was caused by a third-party plugin for Magento\Store\Model\Store::isUseStoreInUrl(). 
Sorry for bothering you and thank you for help.

**Comment by bbutkovic** [comment] 2023-03-02 08:12
@mykolaoleksiuk glad you got it fixed.

Despite the issue not being related to us, I took the opportunity to add some tests for the URL rewrite logic in our Magento module that tests against various different configuration and URL variations. We can close this issue but I'll add the test cases for future reference.

cc: @vvuksan

**Closed** 2023-03-14 14:05 UTC
